name: 'data_pipeline'
config-version: 2
version: 1.0.0

profile: 'data_pipeline'

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"

quoting:
    database: true
    schema: true
    identifier: true

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
    data_pipeline:
        sources:
            wilson_test:
                schema: wilson_test
                materialized: view
            LAN:
                schema: 45991883
                materialized: view
        stages:
            tracking_stage:
                schema: tracking_stage
                materialized: view
        destinations:
            marts:
                schema: marts
                materialized: view
            Ads_and_Promotion:
                schema: Ads_and_Promotion
                materialized: view
