data_pipeline:
  target: loreal_bq
  outputs:
    loreal_bq:
      type: bigquery
      method: service-account
      keyfile: /var/secrets/google/service-account.json
      dataset: wilson_test
      project: loreal-tw
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
    dev:
      type: bigquery
      method: oauth
      project: loreal-tw
      dataset: wilson_test
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive