version: 2

sources:
  - name: tracking_YSL
    database: 'loreal-tw'
    schema: '90742758'
    description: Yves Saint Laurent

    quoting:
      database: true
      schema: true
      identifier: true

    tables:
      - name: ga_sessions_*