version: 2

sources:
  - name: tracking_KLS
    database: 'loreal-tw'
    schema: '59637441'
    description: Kiehl's

    quoting:
      database: true
      schema: true
      identifier: true

    tables:
      - name: ga_sessions_*